# Generated by Django 3.1.4 on 2021-12-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='font_color',
            field=models.CharField(default='font', max_length=7),
            preserve_default=False,
        ),
    ]
