# Generated by Django 3.1.4 on 2021-12-13 21:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitesettings_font_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_subtitle', models.CharField(max_length=450)),
                ('project_description', tinymce.models.HTMLField()),
            ],
        ),
    ]
