# Generated by Django 3.1.4 on 2021-12-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='entry_section_background',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
    ]
