# Generated by Django 3.1.4 on 2021-12-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='Project',
        ),
        migrations.AddField(
            model_name='project',
            name='Images',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.projectimage'),
        ),
    ]
