# Generated by Django 3.1.4 on 2021-12-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211216_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='entry_section_background',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
