# Generated by Django 3.1.4 on 2022-04-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211220_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=455)),
                ('job', models.CharField(max_length=455)),
                ('start_date', models.CharField(max_length=455)),
                ('end_date', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=455)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
