# Generated by Django 3.1.4 on 2022-05-16 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image_shadow',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
